### PR TITLE
Speedup activate by skip package name inference && defer module require

### PR DESCRIPTION
**Pull request by ypresto**
### Expected behaviour: 

image

to

image

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Is 0aac689b71cddf94c5aa2ac3b533af75419d1893 actually changing that time at all? It shouldn't be...

**Comment by ypresto** [comment]
Yes, because providerLinter called on package activation:

image

**Comment by Arcanemagus** [comment]
Oh interesting, I was under the impression that it only was called when linter consumed the service it provides. I wonder why it is being called on activate as that makes _no_ sense.

If that is the case, can you change those to (script) global variables that cache the require, so each would be something like:

```coffeescript
@globule = null
# ...
  provideLinter: ->
    @globule = require 'globule' if not @globule?
```

**Comment by ypresto** [comment]
> why it is being called on activate as that makes no sense

The service also provides metadata like what file types are supported and lintOnFly flag. So linter should consume ALL services before it runs any linter.

```
grammarScopes: ['source.css.scss', 'source.scss', 'source.css.sass', 'source.sass']
...
lintOnFly: true
```

> cache the require

`require()` itself caches loaded module, so it has no difference on performance :)

**Comment by Arcanemagus** [comment]
Whoops, meant to merge this when I posted that comment. 😛

> `require()` itself caches loaded module, so it has no difference on performance :)

That's what I always thought, then I was told otherwise, and I haven't bothered to dig into it yet to find the truth.

**Comment by DanPurdy** [comment]
Thanks for this @ypresto I'll release this soon as v1.7.0 👍

**Comment by DanPurdy** [comment]
Released in 1.7.0

**Pull request merged**
