### PR TITLE
Update package dependencies

### LINKED ISSUE #33: Update dependencies recently locked down
`consistent-path` and `atom-package-deps` have had their versions locked down here to prevent tests failing before i have time to investigate. They will need to be updated to the latest versions again manually.

### PR DESCRIPTION
**Pull request by DanPurdy**
Closes #33

### CODE REVIEW

**Comment by DanPurdy** [comment]
@Arcanemagus @steelbrain so looking at the results of this it seems that when using spawn sync to run the `npm get prefix` command it actually returns the wrong path on osx

I'm using nvm and `npm get prefix` returns `/Users/danpurdy/.nvm/versions/node/v4.2.4` when atom runs it itself it gets `/usr/local/Cellar/node/4.1.1`

Travis is itself using nvm so I'm assuming there's some sort of mismatch here.

**Comment by DanPurdy** [comment]
So updating npm fixes this, but clearly the version being used on travis isn't working.. Very strange...

**Comment by Arcanemagus** [comment]
Is Travis actually using `nvm` on the OS X builds? As far as I know they have no official support for anything other than Objective-C on there. You can check out [`package-deps:/travis.yml`](https://github.com/steelbrain/package-deps/blob/master/.travis.yml) for an example of how to setup Node v5 properly on Travis.

**Comment by DanPurdy** [comment]
I was sure they were, either way they're using node 0.10 and npm 2.x which is failing with getting the correct path now I've recreated it locally too so I'm not sure if 'consistent psth

**Comment by Arcanemagus** [comment]
Try forcing an update to Node in the manner that linked `.travis.yml` does and see if things improve?

**Comment by DanPurdy** [comment]
Sorry my fat fingers posted that before I'd finished, I know updating node would fix it but this seems to be a regression in a currently supported version of node.. We still test sass-lint itself against 0.10 all the way up to v5 on Travis

**Comment by Arcanemagus** [comment]
Hmmm, so recently `consistent-path` was changed so that instead of taking the current $PATH, the additions it is making, and merging them together in a random order it now takes $PATH, adds anything it is going to add (no duplications) _to the end_, and returns that.

I was seeing an issue with the builds in `linter-php` that exposed that the updated $PATH I was creating before starting Atom wasn't actually being used due to `consistent-path`, which is how we discovered that issue.

Are you running OS X locally? `consistent-path` shouldn't be changing anything on non-OSX platforms.

**Comment by DanPurdy** [comment]
Yep I'm running osx here, it failed and reported the wrong path before I updated to npm v3.x then it passed fine..

**Comment by Arcanemagus** [comment]
So what does `process.env.PATH` look like before and after `consistent-path` is ran?

**Comment by DanPurdy** [comment]
I don't know anymore, get them to fail locally again :(

**Comment by DanPurdy** [comment]
closing in favour of #46

**Pull request closed without merging**
